# Generated by Django 4.2.16 on 2025-01-14 08:40

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.PositiveSmallIntegerField(choices=[(1, 'administardor'), (2, 'visitante'), (3, 'responsable')], default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('biografia', models.TextField()),
                ('nacionalidad', models.CharField(blank=True, choices=[('espanola', 'Española'), ('italiana', 'Italiana')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, default='', null=True)),
                ('capacidad', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('idiomas', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('disponibilidad', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vendida', models.IntegerField(default=0)),
                ('fecha_ultima_venta', models.DateField(blank=True, null=True)),
                ('stock_inicial', models.IntegerField(default=100)),
                ('ubicacion_almacen', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Museo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del museo')),
                ('ubicacion', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('fecha_fundacion', models.DateField(help_text='Fecha en que se fundo el museo', null=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField(null=True)),
                ('fecha_visita', models.DateField()),
                ('museo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitantes', to='appmuseo.museo')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitaGuiada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.DurationField()),
                ('nombre_visita_guia', models.CharField(max_length=100)),
                ('capacidad_maxima', models.IntegerField(default=20)),
                ('idioma', models.CharField(choices=[('espanol', 'Español'), ('ingles', 'Inglés')], max_length=50)),
                ('guias', models.ManyToManyField(related_name='visita_guiada_guia', to='appmuseo.guia')),
                ('visitantes', models.ManyToManyField(related_name='visita_guiada_visitante', to='appmuseo.visitante')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('museo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmuseo.museo')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmuseo.visitante')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
                ('museo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tienda', to='appmuseo.museo')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('stock', models.IntegerField(default=0)),
                ('tiendas', models.ManyToManyField(related_name='productos_tienda', through='appmuseo.Inventario', to='appmuseo.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la obra')),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('pintura', 'Pintura'), ('escultura', 'Escultura')], default='pintura', max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='obras/')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_artista', to='appmuseo.artista')),
                ('exposicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_exposicion', to='appmuseo.exposicion')),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_producto', to='appmuseo.producto'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_tienda', to='appmuseo.tienda'),
        ),
        migrations.AddField(
            model_name='guia',
            name='museo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias', to='appmuseo.museo'),
        ),
        migrations.AddField(
            model_name='exposicion',
            name='museo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposiciones', to='appmuseo.museo'),
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipo', models.CharField(choices=[('adulto', 'Adulto'), ('nino', 'Niño')], max_length=50)),
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('visitante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='appmuseo.visitante')),
            ],
        ),
    ]
